version: '3.1'

services:
  maria_prisma_db:
    image: postgres
    restart: always
    container_name: maria_prisma_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"